# Generated by Django 4.1.3 on 2022-11-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch", old_name="branches", new_name="districts",
        ),
    ]
