# Generated by Django 4.1.3 on 2022-11-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0002_rename_branches_branch_districts"),
    ]

    operations = [
        migrations.DeleteModel(name="Branch",),
        migrations.DeleteModel(name="District",),
    ]
